GET http://localhost:8080/api/users

### add user

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Idea User1",
  "lastName": "Idea User lastname1",
  "email": "user@jetbrains.com1",
  "password": "12345Qwerty1"
}

### update user

PUT http://localhost:8080/api/users/5
Content-Type: application/json

{
  "firstName": "Updated User",
  "lastName": "Updated Lastname"
}


### delete user
DELETE http://localhost:8080/api/users/5
